### PR TITLE
added unit tests, methods, and more for finishing multiplication implementation

### PR DESCRIPTION
**Pull request by AaronKutch**
added some methods to Digit and DoubleDigit for convenience, added `wrapping_inc` and fixed `negate`, replaced the unimplemented! section in the checked_mul_assign function, and added a rigorous unit test.

### CODE REVIEW

**Comment by Robbepop** [comment]
I have looked over the code and comments and it looks really good to me! :)

**Comment by Robbepop** [comment]
Do you want me to merge it asap?

**Comment by AaronKutch** [comment]
merge it. Next pull request I plan on looking at some of the other arithmetic functions and see if benchmarks improve when I make some changes. After that, I will pull request my division function, and then after that is the name changing. I would also try SIMD, but unfortunately I need to get back to my project. Maybe some time in the future I can come back and do SIMD and Karatsuba.

**Comment by Robbepop** [comment]
Thank you for all the glorious work - it is amazing! :tada: 

I will merge this and release a 0.3 version of the apint crate.

**Pull request merged**
