### PR TITLE
Fix critical bug in multiplication of large odd-width instances

### PR DESCRIPTION
**Pull request by AaronKutch**
I was working on making a better fuzz tester when I discovered a flaw that the old 0.2.0 tester missed. Overflowing multiplication using `ApInt`s with a bit width that is not a multiple of `Digit`s could sometimes not erase the excess bits in the last `Digit`, violating an invariant. It is unlikely that someone is using multiplication, wierd width `ApInt`s, and overflowing the multiplication at the same, but this should still be merged as soon as possible, given a commit to update the changelog and bump version to 0.2.1, and released.

### CODE REVIEW

**Comment by Robbepop** [comment]
Good catch!
We should really write some contribution guidelines so that new code is always tested for all relevant scenarios and special cases and widths. E.g. bit widths of 1, 2, 8, 16, 32, 64, 128, 256, 512, 1024, 50, 100, 1000, etc. That's at least what I always targeted to do whenever I was testing new code. This, however, is really cumbersome and you can imagine ...

**Comment by AaronKutch** [comment]
I have a regression test and a greatly improved fuzz tester (it tests a great variety of widths and has a proper overflowing multiplication test, and I have added more shifting and division tests) in my reorganization branch. I am confident now that all the arithmetic ops are working in both my branch and in the current master.

**Comment by Robbepop** [comment]
> I have a regression test and a greatly improved fuzz tester (it tests a great variety of widths and has a proper overflowing multiplication test, and I have added more shifting and division tests) in my reorganization branch. I am confident now that all the arithmetic ops are working in both my branch (edit: my local branch, I need to do some more things before I push it to the PR) and in the current master.

Ah very nice!
So could you move the regression test for this bug over to this PR so it is self contained? (CI etc.)
I would merge it as soon as CI passes it.

**Comment by AaronKutch** [comment]
I backported some chunks of code from the newer fuzz tester and found an arithmetic shift right bug in your old code, again regarding odd-width instances. In my local branch I rewrote the shifting functions before I made the newer fuzz tester so I didn't catch this. I have also backported the new arithmetic shifting function to fix this.

**Comment by Robbepop** [comment]
Okay so I think this is ready for merge.

**Comment by Robbepop** [comment]
Thanks a lot for fixing this!

**Pull request merged**
