### PR TITLE
Remove libm dependency and fix compilation error

### PR DESCRIPTION
**Pull request by AaronKutch**
The compilation error only happened if compiled with `serde_support`

### CODE REVIEW

**Comment by AaronKutch** [comment]
Should the tests work in `no_std`? If so, I can add a `cfg` to the one test with `log2`.

**Comment by AaronKutch** [comment]
I think we should always run tests with the default set of features and only worry about the build working in other cases.

**Comment by AaronKutch** [comment]
Are you waiting to merge it? I am confused about the purpose of just approving a PR.

**Comment by Robbepop** [comment]
> Are you waiting to merge it? I am confused about the purpose of just approving a PR.

I was on my phone, not laptop. Also I am curious why CI fails for this PR. Let me check.

**Comment by Robbepop** [comment]
> Should the tests work in `no_std`? If so, I can add a `cfg` to the one test with `log2`.

Tests don't have to work for `no_std` but `build` does.

**Comment by AaronKutch** [comment]
Thanks for clearing that up.

**Comment by Robbepop** [comment]
I just restarted the Travis CI job.

**Comment by AaronKutch** [comment]
Its still timing out for some reason

**Comment by Robbepop** [comment]
Dont know why but looks odd to me.

**Pull request merged**
