### PR TITLE
Fix various trait problems

### PR DESCRIPTION
**Pull request by AaronKutch**
This starts by renaming `traits.rs` to `width.rs` to avoid name collisions. I decided in the middle to name the new file `std_ops.rs`, but I still think it is a better name.

I then simplify all the imports (just changing stuff like `crate::bitwidth::BitWidth` to `crate::BitWidth`).  I encountered a weird rustfmt bug in `constructors.rs`, so I just put a `#[rustfmt::skip]` and `TODO` on the affected macro.

The next commit gathers creates a new `std_ops.rs` file which will contain all `std::ops` functionality except for `Drop`. I deleted every other impl in the crate because they used inconsistent signatures and used cloning inside them.

The next commit does the same for `UInt`s and `Int`s. The diff is pretty confusing, but I just indented the impls into a new macro that handles `ApInt`, `UInt`, and `Int` at the same time. No more need to check all duplicate impls around the crate for typos.

The next commit updates the docs and the final commit adds some missing `Width` implementations.

### CODE REVIEW

**Comment by AaronKutch** [comment]
Wow I wasn't expecting you to approve it so quickly. It is ready for merging.

**Comment by AaronKutch** [comment]
wait I forgot to test for no-std compatibility

**Comment by AaronKutch** [comment]
If you can I would add to the CI a test that just does `cargo build --no-default-features` and see if it compiles without errors. Also, I don't think there is a rustfmt test either.

**Comment by Robbepop** [comment]
> If you can I would add to the CI a test that just does `cargo build --no-default-features` and see if it compiles without errors. Also, I don't think there is a rustfmt test either.

I'd love to see an improved CI. Go ahead but please do this in another PR. I will merge this now. ;) Thanks.

**Pull request merged**
